
spring:
  profiles:
    active: dev
  ## 数据源配置
  datasource:
    url: jdbc:mysql://mysql57.rdsmz60przasm9w.rds.bj.baidubce.com:3306/ksp?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: aesop
    password: aesop_123
    driver-class-name: com.mysql.jdbc.Driver

  #静态资源配置
  resources:
    static-locations: classpath:/static/

  #热部署生效
  devtools:
    restart:
      enabled: false #TODO 暂时关闭
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      #exclude: WEB-INF/**

  #邮件配置
  mail:
    host: smtp.163.com
    username: chao_c_c@163.com
    password: chao123
    port: 465
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

## mybatis配置
mybatis:
  typeAliasesPackage: cn.kspshare.domain #实体类包路径
  mapperLocations: classpath:mapper/*.xml




#SQL打印 level下面指定mybatis对应的方法接口所在的包
logging:
  level:
     cn.kspshare.dao : debug
     cn.kspshare.mapper : debug

#自定义配置
ksp:
  #token失效时长，单位：秒，86400表示1天
  jwtExpiredSecend: 86400