#端口
server:
  port: 8080

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
## mybatis配置
mybatis:
  typeAliasesPackage: cn.kspshare.domain #实体类包路径
  mapperLocations: classpath:mapper/*.xml

#SQL打印 level下面指定mybatis对应的方法接口所在的包
logging:
  level:
     cn.kspshare.dao : debug
     cn.kspshare.mapper : debug