#端口
server:
  port: 8083

spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://mysql57.rdsmz60przasm9w.rds.bj.baidubce.com:3306/ksp?useSSL=false&useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://localhost:3306/ksp?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: aesop
    password: aesop_123
    driver-class-name: com.mysql.jdbc.Driver

  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      #exclude: WEB-INF/**